/*
 * generated by Xtext 2.21.0
 */
package org.eclipse.acme


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ACMECNlRuntimeModule extends AbstractACMECNlRuntimeModule {
	override bindIQualifiedNameProvider() {
		return CnlQNP;
	}
}
