/*
 * generated by Xtext 2.21.0
 */
package org.eclipse.acme.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.acme.ACMECNlRuntimeModule;
import org.eclipse.acme.ACMECNlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ACMECNlIdeSetup extends ACMECNlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ACMECNlRuntimeModule(), new ACMECNlIdeModule()));
	}
	
}
