<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cnl" nsURI="http://org.eclipse.acme/cnl" nsPrefix="acmecnl_">
  <eClassifiers xsi:type="ecore:EClass" name="ConstrainedNaturalLanguageRules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//ValidationRules" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" upperBound="-1"
        eType="#//MetaData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationRules"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScopedRules" eSuperTypes="#//ValidationRules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1" eType="#//ElementScope"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true" eOpposite="#//Rule/scopedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchScopedRule" eSuperTypes="#//ValidationRules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1"
        eType="#//MatchingRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatchingRule" eSuperTypes="#//CNLRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1" eType="#//ElementScope"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementScope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopedBy" eType="#//ScopedRules"
        eOpposite="#//ScopedRules/rules"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CNLRule" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="astRoot" lowerBound="1"
        eType="#//Expression" containment="true" eOpposite="#//Expression/rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GPLRule" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EOLExpressionRule" eSuperTypes="#//GPLRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="info" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//CNLRule"
        eOpposite="#//CNLRule/astRoot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EqualityExpression" eSuperTypes="#//ComparisonExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="NegatedEqualityExpression" eSuperTypes="#//ComparisonExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="GreaterThanExpression" eSuperTypes="#//ComparisonExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LessThanExpression" eSuperTypes="#//ComparisonExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="GTEExpression" eSuperTypes="#//ComparisonExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LTEExpression" eSuperTypes="#//ComparisonExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ArithmeticOperations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImpliesExpression" eSuperTypes="#//LogicalExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrExpression" eSuperTypes="#//LogicalExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="XorExpression" eSuperTypes="#//LogicalExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndExpression" eSuperTypes="#//LogicalExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfandonlyifExpression" eSuperTypes="#//LogicalExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BaseExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//BaseExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//BaseExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeforeDateExpression" eSuperTypes="#//DateExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="AfterDateExpression" eSuperTypes="#//DateExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="OnorbeforeDateExpression" eSuperTypes="#//DateExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="OnorafterDateExpression" eSuperTypes="#//DateExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureValue" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//ElementScope"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeExpression" abstract="true" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//FeatureValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeExpression" eSuperTypes="#//TypeExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PrimitiveTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumTypeExpression" eSuperTypes="#//TypeExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Enum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericAggregation" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//FeatureValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericSummation" eSuperTypes="#//NumericAggregation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericAverage" eSuperTypes="#//NumericAggregation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericMaximum" eSuperTypes="#//NumericAggregation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericMinimum" eSuperTypes="#//NumericAggregation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueContainment" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//FeatureValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" lowerBound="1"
        upperBound="-1" eType="#//BaseExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniquenessCheck" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" lowerBound="1"
        upperBound="-1" eType="#//FeatureValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringValue" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumValue" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" lowerBound="1"
        eType="#//Enum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValue" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValue" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecimalValue" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateValue" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmptyValue" eSuperTypes="#//BaseExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExistanceValue" eSuperTypes="#//BaseExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="MetaData" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="legalValues" upperBound="-1"
        eType="#//MetaValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaValue" abstract="true" eSuperTypes="#//BaseExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumerations" eSuperTypes="#//MetaData"/>
  <eClassifiers xsi:type="ecore:EClass" name="Types" eSuperTypes="#//MetaData"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//MetaValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//MetaValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//MetaValue"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOperations">
    <eLiterals name="plus"/>
    <eLiterals name="minus" value="1"/>
    <eLiterals name="times" value="2"/>
    <eLiterals name="div" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveTypes">
    <eLiterals name="String"/>
    <eLiterals name="Boolean" value="1"/>
    <eLiterals name="Integer" value="2"/>
    <eLiterals name="Decimal" value="3"/>
    <eLiterals name="Date" value="4"/>
  </eClassifiers>
</ecore:EPackage>
