<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hazardlog" nsURI="http://org.eclipse.acme/1.0/hazardlog" nsPrefix="hazardlog_">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HazardLog" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazards" upperBound="-1"
        eType="#//HazardousSituation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HazardousSituation" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="#//Severity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" eType="#//Probability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="causes" upperBound="-1"
        eType="#//Cause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cause" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlMeasure" upperBound="-1"
        eType="#//ControlMeasure" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlMeasure" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="safetyDecisionRationale"
        eType="#//SafetyDecisionRationale" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verificationofEffectiveness"
        upperBound="-1" eType="#//VerificationofEffectiveness" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validation" upperBound="-1"
        eType="#//Validation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerificationofEffectiveness" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Validation" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyDecisionRationale" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Severity">
    <eLiterals name="catastrophic" value="1"/>
    <eLiterals name="critical" value="2"/>
    <eLiterals name="serious" value="3"/>
    <eLiterals name="minor" value="4"/>
    <eLiterals name="negligible" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Probability">
    <eLiterals name="frequent" value="1"/>
    <eLiterals name="probable" value="2"/>
    <eLiterals name="occasional" value="3"/>
    <eLiterals name="remote" value="4"/>
    <eLiterals name="improbable" value="5"/>
  </eClassifiers>
</ecore:EPackage>
