/*
 * generated by Xtext 2.21.0
 */
package org.eclipse.acme.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractACMECNlScopeProvider extends DelegatingScopeProvider {
}
