/*
 * generated by Xtext 2.21.0
 */
package org.eclipse.acme.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ACMECNlUiModule extends AbstractACMECNlUiModule {

	public ACMECNlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
