/**
 */
package cae.provider;

import cae.util.Cae_AdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Cae_ItemProviderAdapterFactory extends Cae_AdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Cae_ItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link cae.CAEModule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CAEModuleItemProvider caeModuleItemProvider;

	/**
	 * This creates an adapter for a {@link cae.CAEModule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCAEModuleAdapter() {
		if (caeModuleItemProvider == null) {
			caeModuleItemProvider = new CAEModuleItemProvider(this);
		}

		return caeModuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cae.CAEModuleInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CAEModuleInterfaceItemProvider caeModuleInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link cae.CAEModuleInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCAEModuleInterfaceAdapter() {
		if (caeModuleInterfaceItemProvider == null) {
			caeModuleInterfaceItemProvider = new CAEModuleInterfaceItemProvider(this);
		}

		return caeModuleInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cae.CAEModuleBinding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CAEModuleBindingItemProvider caeModuleBindingItemProvider;

	/**
	 * This creates an adapter for a {@link cae.CAEModuleBinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCAEModuleBindingAdapter() {
		if (caeModuleBindingItemProvider == null) {
			caeModuleBindingItemProvider = new CAEModuleBindingItemProvider(this);
		}

		return caeModuleBindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cae.CAEClaim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CAEClaimItemProvider caeClaimItemProvider;

	/**
	 * This creates an adapter for a {@link cae.CAEClaim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCAEClaimAdapter() {
		if (caeClaimItemProvider == null) {
			caeClaimItemProvider = new CAEClaimItemProvider(this);
		}

		return caeClaimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cae.Argument} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArgumentItemProvider argumentItemProvider;

	/**
	 * This creates an adapter for a {@link cae.Argument}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArgumentAdapter() {
		if (argumentItemProvider == null) {
			argumentItemProvider = new ArgumentItemProvider(this);
		}

		return argumentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cae.Evidence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EvidenceItemProvider evidenceItemProvider;

	/**
	 * This creates an adapter for a {@link cae.Evidence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEvidenceAdapter() {
		if (evidenceItemProvider == null) {
			evidenceItemProvider = new EvidenceItemProvider(this);
		}

		return evidenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cae.IsSubClaimOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsSubClaimOfItemProvider isSubClaimOfItemProvider;

	/**
	 * This creates an adapter for a {@link cae.IsSubClaimOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsSubClaimOfAdapter() {
		if (isSubClaimOfItemProvider == null) {
			isSubClaimOfItemProvider = new IsSubClaimOfItemProvider(this);
		}

		return isSubClaimOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cae.Supports} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SupportsItemProvider supportsItemProvider;

	/**
	 * This creates an adapter for a {@link cae.Supports}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSupportsAdapter() {
		if (supportsItemProvider == null) {
			supportsItemProvider = new SupportsItemProvider(this);
		}

		return supportsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link cae.IsEvidenceFor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsEvidenceForItemProvider isEvidenceForItemProvider;

	/**
	 * This creates an adapter for a {@link cae.IsEvidenceFor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsEvidenceForAdapter() {
		if (isEvidenceForItemProvider == null) {
			isEvidenceForItemProvider = new IsEvidenceForItemProvider(this);
		}

		return isEvidenceForItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (caeModuleItemProvider != null) caeModuleItemProvider.dispose();
		if (caeModuleInterfaceItemProvider != null) caeModuleInterfaceItemProvider.dispose();
		if (caeModuleBindingItemProvider != null) caeModuleBindingItemProvider.dispose();
		if (caeClaimItemProvider != null) caeClaimItemProvider.dispose();
		if (argumentItemProvider != null) argumentItemProvider.dispose();
		if (evidenceItemProvider != null) evidenceItemProvider.dispose();
		if (isSubClaimOfItemProvider != null) isSubClaimOfItemProvider.dispose();
		if (supportsItemProvider != null) supportsItemProvider.dispose();
		if (isEvidenceForItemProvider != null) isEvidenceForItemProvider.dispose();
	}

}
